### ISSUE TITLE
Cannot set up splunk

### ISSUE THREAD

**Issue by venom861** [sakshamtushar/thor-detection-lab#2]
![thorlab-issue](https://github.com/user-attachments/assets/bad772ff-baf2-4099-b47d-4cb6afff1ec2)

Hi thanks for creating this setup, there seems to be a problem with finding the docker compose file for splunk when option 1 is chosen

**Comment by sakshamtushar** [comment]
Standardized docker-compose.yml file-names inside the tools folders, 
This should work now!!
